version: '2'
services:
  #database : mongo db
  mongo:
    image: mongo:latest
    volumes:
    - /opt/mongodb/db-home-advisor:/data/db
    restart: always
  #rest api engie : node + code
  load-balancer-api:
    ports:
    - ${HOST_PORT_API}
    image: rancher/lb-service-haproxy:v0.6.4
    labels:
      proxy_url: ${EXPOSE_API_URL}
      io.rancher.scheduler.affinity:host_label: master=1
  api:
    image: krack/home-advisor-api:${TAG}
    links:
    - mongo
    restart: always
    environment:
    - ALLOW_URL=http://${EXPOSE_SITE_URL}
    - SERVER_HOST=http://${EXPOSE_API_URL}
    - SERVER_PORT=${HOST_PORT_API}
    - SERVER_PUBLIC_PORT=80
    - FACEBOOK_API_KEY=${FACEBOOK_API_KEY}
    - FACEBOOK_API_SECRET=${FACEBOOK_API_SECRET}
    labels:
      io.rancher.container.pull_image: always
  #web site : static with apache
  load-balancer-web:
    ports:
    - ${HOST_PORT_WEB}
    image: rancher/lb-service-haproxy:v0.6.4
    labels:
      proxy_url: ${EXPOSE_SITE_URL}
      io.rancher.scheduler.affinity:host_label: master=1
  web:
    image: httpd:2.4
    image: krack/home-advisor-web:${TAG}
    restart: always
    labels:
      io.rancher.container.pull_image: always
